services:
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,
      - AWS_DEFAULT_REGION=us-east-1
      - LS_LOG=info
      - PERSISTENCE=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
      - "./lambdas:/lambdas"
      - "./scripts:/scripts"